### ISSUE TITLE
Calculating Financial Outlay

### ISSUE THREAD

**Issue by kaizer1v** [DataKind-BLR/panoptic_flask#17]
Traceback (most recent call last):
  File "panoptic_flask.py", line 62, in <module>
    print(model.get_state_page_data('Karnataka'))
  File "/media/vivek/Stuff/datakind/Iff_frt/panoptic_flask/model/model.py", line 68, in get_state_page_data
    'financial_outlay_cr': utils._sum_state_financial_outlay(state_frts),
  File "/media/vivek/Stuff/datakind/Iff_frt/panoptic_flask/model/utils.py", line 19, in _sum_state_financial_outlay
    total_financial_outlay += result['financial_outlay_cr']
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

**Comment by kaizer1v** [comment]
sample response for `results` parameter for the `_count_frt_use` function

`[{'name': None, 'in_use': 0, 'purpose': None, 'report_use_on': None, 'rti_filed_on': None, 'financial_outlay_cr': None, 'media_source': None, 'rti_response': None}]`

**Comment by romitjain** [comment]
@kaizer1v Made these changes in the `dev` branch. This should not give errors anymore, can you please check?

**Comment by romitjain** [comment]
This should be resolved now
