### ISSUE TITLE
[Bug] Not able to access the website

### ISSUE THREAD

**Issue by romitjain** [DataKind-BLR/panoptic_flask#4]
When trying to access the website, it gives an internal error.
The error log on the server is as follows:

```
[Mon Aug 03 13:58:51.307082 2020] [wsgi:info] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639] mod_wsgi (pid=1981, process='', application='3.7.235.141|/panoptic'): Loading WSGI script '/var/www/panoptic_flask/panoptic_flask.wsgi'.
[Mon Aug 03 13:58:51.577914 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639] mod_wsgi (pid=1981): Target WSGI script '/var/www/panoptic_flask/panoptic_flask.wsgi' cannot be loaded as Python module.
[Mon Aug 03 13:58:51.577939 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639] mod_wsgi (pid=1981): Exception occurred processing WSGI script '/var/www/panoptic_flask/panoptic_flask.wsgi'.
[Mon Aug 03 13:58:51.577974 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639] Traceback (most recent call last):
[Mon Aug 03 13:58:51.577996 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]   File "/var/www/panoptic_flask/panoptic_flask.wsgi", line 12, in <module>
[Mon Aug 03 13:58:51.578046 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]     from panoptic_flask import app as application
[Mon Aug 03 13:58:51.578058 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]   File "/var/www/panoptic_flask/panoptic_flask/panoptic_flask.py", line 2, in <module>
[Mon Aug 03 13:58:51.578090 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]     from folium_map import generate_map
[Mon Aug 03 13:58:51.578149 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]   File "/var/www/panoptic_flask/panoptic_flask/folium_map.py", line 124
[Mon Aug 03 13:58:51.578156 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]     html = f'''
[Mon Aug 03 13:58:51.578160 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]         <h1>Name: </h1>{state}<br />\\
[Mon Aug 03 13:58:51.578164 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]         <h2>Location: </h2>{auth}<br />\\
[Mon Aug 03 13:58:51.578168 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]         <a href="about:blank">More Details</a>
[Mon Aug 03 13:58:51.578172 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]         '''
[Mon Aug 03 13:58:51.578176 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]
[Mon Aug 03 13:58:51.578179 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]
[Mon Aug 03 13:58:51.578183 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]
[Mon Aug 03 13:58:51.578186 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]
[Mon Aug 03 13:58:51.578190 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639]           ^
[Mon Aug 03 13:58:51.578194 2020] [wsgi:error] [pid 1981:tid 140264840623872] [client 103.82.80.33:52639] SyntaxError: invalid syntax
```

**Comment by SrivalyaElluru** [comment]
f''' is the error . Put the f inside the comment. '''    ''' 

@romitjain @SrihariPramod

**Comment by romitjain** [comment]
This is fixed now
